/**
 * deploy-data-subject-rights.ts — Deploy DataSubjectRights to Midnight Network
 *
 * Tracks LGPD Art. 18 rights requests and Art. 19 response deadlines on-chain.
 * Third pillar of the DPO2U compliance suite (alongside ConsentRegistry + DataAuditLog).
 *
 * Usage:
 *   npx tsx scripts/deploy-data-subject-rights.ts [options]
 *
 * Options:
 *   --network   preprod | preview | standalone  (default: preprod)
 *   --seed      <64-char hex>  HD wallet seed
 *   --join      <contract-address>  join existing deployment
 *   --faucet    request tNIGHT from faucet (preprod/preview only)
 *   --demo      run demo: submit/fulfill/reject/overdue request lifecycle
 *
 * Prerequisites:
 *   1. compactc 0.29.0 installed + Bug 1 fix applied (see scripts/compile-contracts.sh)
 *   2. ./scripts/compile-contracts.sh --contract DataSubjectRights
 *   3. rm -f .npmrc  (Bug 2: npm.midnight.network does not exist)
 *   4. npm install
 *   5. Proof server running on port 6300 (docker-compose up -d)
 *
 * SDK Versions (PREPROD — SDK-VERSION-MATRIX.md):
 *   @midnight-ntwrk/midnight-js-*       3.0.0–3.1.0
 *   @midnight-ntwrk/wallet-sdk-facade   2.0.0  (WalletFacade.init API)
 *   @midnight-ntwrk/ledger-v7           7.0.0
 *   @midnight-ntwrk/compact-runtime     0.14.0
 *   midnight-node Docker                0.21.0
 *   indexer-standalone Docker           3.1.0
 *   proof-server Docker                 7.0.0
 *
 * CRITICAL RULES from WORKAROUND-GUIDE.md:
 *   - NEVER use npm.midnight.network (does not exist — Bug 2)
 *   - NEVER mix preprod/preview SDK versions (silent sync failures — Bug 3)
 *   - NEVER use wallet.signRecipe() — use WalletFacade.init + finalizeRecipe (Bug 5)
 *   - ALWAYS call setNetworkId() before any contract operation
 *   - ALWAYS add smoldot override to package.json (Bug 7)
 *
 * LGPD Coverage:
 *   Art. 18 I–IX  rights requests (9 request types)
 *   Art. 19       15-day response deadline enforcement (21600 blocks at 1 block/min)
 *   Art. 18 §4    rejection with justification (recorded on-chain, reason off-chain)
 */

import 'dotenv/config';
import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import {
  type MidnightProvider,
  type WalletProvider,
  type MidnightProviders,
} from '@midnight-ntwrk/midnight-js-types';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { toHex } from '@midnight-ntwrk/midnight-js-utils';
import { CompiledContract, type ImpureCircuitId } from '@midnight-ntwrk/compact-js';

import { WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { DustWallet } from '@midnight-ntwrk/wallet-sdk-dust-wallet';
import { HDWallet, Roles, generateRandomSeed } from '@midnight-ntwrk/wallet-sdk-hd';
import { ShieldedWallet } from '@midnight-ntwrk/wallet-sdk-shielded';
import {
  createKeystore,
  PublicKey,
  UnshieldedWallet,
} from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import * as ledgerLib from '@midnight-ntwrk/ledger-v7';

// Generated by: ./scripts/compile-contracts.sh --contract DataSubjectRights
import * as DataSubjectRights from '../build/DataSubjectRights/contract/index.js';

import * as Rx from 'rxjs';
import { WebSocket } from 'ws';
import { Buffer } from 'buffer';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { parseArgs } from 'node:util';
import * as fs from 'node:fs';

// WebSocket polyfill required by GraphQL subscriptions in Node.js
// @ts-expect-error: global override for graphql-ws
globalThis.WebSocket = WebSocket;

// ------------------------------------------------------------------
// Types
// ------------------------------------------------------------------
type PrivateState = Record<string, never>;
type DataSubjectRightsContract = DataSubjectRights.Contract<PrivateState>;
type CircuitIds = ImpureCircuitId<DataSubjectRightsContract>;

const PRIVATE_STATE_ID = 'dataSubjectRightsPrivateState' as const;
type Providers = MidnightProviders<CircuitIds, typeof PRIVATE_STATE_ID, PrivateState>;

// ------------------------------------------------------------------
// Network Configuration
// Matches SDK-VERSION-MATRIX.md verified combinations
// ------------------------------------------------------------------
interface NetworkConfig {
  indexer: string;
  indexerWS: string;
  node: string;
  proofServer: string;
  networkId: string;
  faucetUrl?: string;
}

const NETWORKS: Record<string, NetworkConfig> = {
  preprod: {
    indexer: 'https://indexer.preprod.midnight.network/api/v3/graphql',
    indexerWS: 'wss://indexer.preprod.midnight.network/api/v3/graphql/ws',
    node: 'https://rpc.preprod.midnight.network',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'preprod',
    faucetUrl: 'https://faucet.preprod.midnight.network/api/request-tokens',
  },
  preview: {
    indexer: 'https://indexer.preview.midnight.network/api/v3/graphql',
    indexerWS: 'wss://indexer.preview.midnight.network/api/v3/graphql/ws',
    node: 'https://rpc.preview.midnight.network',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'preview',
    faucetUrl: 'https://faucet.preview.midnight.network/api/request-tokens',
  },
  standalone: {
    indexer: 'http://127.0.0.1:8088/api/v3/graphql',
    indexerWS: 'ws://127.0.0.1:8088/api/v3/graphql/ws',
    node: 'http://127.0.0.1:9944',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'undeployed',
  },
};

// ------------------------------------------------------------------
// ZK Assets path (output of compactc compilation)
// ------------------------------------------------------------------
const ZK_CONFIG_PATH = path.resolve(
  new URL(import.meta.url).pathname,
  '..', '..', 'build', 'DataSubjectRights',
);

// ------------------------------------------------------------------
// Compiled Contract
// ------------------------------------------------------------------
const compiledContract = CompiledContract.make(
  'DataSubjectRights',
  DataSubjectRights.Contract,
).pipe(
  CompiledContract.withVacantWitnesses,
  CompiledContract.withCompiledFileAssets(ZK_CONFIG_PATH),
);

// ------------------------------------------------------------------
// HD Key Derivation (64-char hex seed → shielded + dust + unshielded keys)
// ------------------------------------------------------------------
function deriveKeys(seed: string) {
  const hd = HDWallet.fromSeed(Buffer.from(seed, 'hex'));
  if (hd.type !== 'seedOk') throw new Error('Bad HD seed — must be 64 hex chars');

  const result = hd.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust])
    .deriveKeysAt(0);

  if (result.type !== 'keysDerived') throw new Error('Key derivation failed');
  hd.hdWallet.clear();
  return result.keys;
}

// ------------------------------------------------------------------
// Wallet initialization — WalletFacade.init() API (wallet-sdk-facade 2.0.0)
// See SDK-VERSION-MATRIX.md for API differences between 1.0.0 and 2.0.0
// ------------------------------------------------------------------
async function buildWallet(config: NetworkConfig, seed: string) {
  console.log('[1/6] Deriving HD keys from seed...');
  const keys = deriveKeys(seed);
  const shieldedSecretKeys = ledgerLib.ZswapSecretKeys.fromSeed(keys[Roles.Zswap]);
  const dustSecretKey = ledgerLib.DustSecretKey.fromSeed(keys[Roles.Dust]);
  const unshieldedKeystore = createKeystore(keys[Roles.NightExternal], config.networkId);

  const walletConfig = {
    networkId: config.networkId,
    indexerClientConnection: {
      indexerHttpUrl: config.indexer,
      indexerWsUrl: config.indexerWS,
    },
    provingServerUrl: new URL(config.proofServer),
    relayURL: new URL(config.node.replace(/^http/, 'ws')),
    costParameters: {
      additionalFeeOverhead: 300_000_000_000_000n,
      feeBlocksMargin: 5,
    },
  };

  console.log('[2/6] Initializing WalletFacade...');
  const wallet = await WalletFacade.init({
    configuration: walletConfig,
    shielded: (cfg: any) => ShieldedWallet(cfg).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (cfg: any) => UnshieldedWallet(cfg).startWithPublicKey(
      PublicKey.fromKeyStore(unshieldedKeystore),
    ),
    dust: (cfg: any) => DustWallet(cfg).startWithSecretKey(
      dustSecretKey,
      ledgerLib.LedgerParameters.initialParameters().dust,
    ),
  });

  return { wallet, shieldedSecretKeys, dustSecretKey, unshieldedKeystore, seed };
}

// ------------------------------------------------------------------
// Wait for wallet sync
// ------------------------------------------------------------------
async function waitForSync(wallet: WalletFacade) {
  console.log('[3/6] Syncing wallet (first sync may take 10-30 min)...');

  const sub = wallet.state().pipe(
    Rx.throttleTime(15_000),
  ).subscribe((state) => {
    const synced = state.isSynced ? 'SYNCED' : 'syncing...';
    const nativeToken = ledgerLib.unshieldedToken().raw;
    const unshieldedBal = state.unshielded?.balances?.[nativeToken] ?? 0n;
    const dustCount = state.dust?.availableCoins?.length ?? 0;
    console.log(`  [${new Date().toISOString().slice(11,19)}] ${synced} | unshielded: ${unshieldedBal} | dust coins: ${dustCount}`);
  });

  try {
    await wallet.waitForSyncedState();
  } finally {
    sub.unsubscribe();
  }
  console.log('  Wallet synced ✓');
}

// ------------------------------------------------------------------
// Balance check + faucet wait
// ------------------------------------------------------------------
async function checkBalance(wallet: WalletFacade): Promise<bigint> {
  const state = await wallet.waitForSyncedState();
  const nativeToken = ledgerLib.unshieldedToken().raw;
  const balance = state.unshielded.balances[nativeToken] ?? 0n;

  if (balance > 0n) {
    console.log(`  tNIGHT balance: ${balance.toLocaleString()}`);
    return balance;
  }

  console.log('  No tNIGHT balance. Waiting for incoming tokens...');
  console.log('  Fund at: https://faucet.preprod.midnight.network/');

  return Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(10_000),
      Rx.filter((s) => s.isSynced),
      Rx.map((s) => s.unshielded.balances[nativeToken] ?? 0n),
      Rx.filter((b) => b > 0n),
    ),
  );
}

// ------------------------------------------------------------------
// Provider bridge — WalletProvider + MidnightProvider
// Bug 5 fix: use finalizeRecipe, NOT wallet.signRecipe() which corrupts proof markers
// ------------------------------------------------------------------
async function createProviderBridge(
  ctx: Awaited<ReturnType<typeof buildWallet>>,
): Promise<WalletProvider & MidnightProvider> {
  const state = await ctx.wallet.waitForSyncedState();
  return {
    getCoinPublicKey: () => state.shielded.coinPublicKey.toHexString(),
    getEncryptionPublicKey: () => state.shielded.encryptionPublicKey.toHexString(),
    async balanceTx(tx: any, ttl?: Date) {
      const recipe = await ctx.wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys: ctx.shieldedSecretKeys, dustSecretKey: ctx.dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      // Bug 5: use finalizeRecipe — do NOT call wallet.signRecipe() directly
      return ctx.wallet.finalizeRecipe(recipe);
    },
    submitTx(tx: any) {
      return ctx.wallet.submitTransaction(tx) as any;
    },
  };
}

// ------------------------------------------------------------------
// Configure all midnight-js providers
// Bug 6 fix: pass walletProvider to levelPrivateStateProvider
// ------------------------------------------------------------------
async function configureProviders(
  ctx: Awaited<ReturnType<typeof buildWallet>>,
  config: NetworkConfig,
): Promise<Providers> {
  const bridge = await createProviderBridge(ctx);
  const zkConfigProvider = new NodeZkConfigProvider<CircuitIds>(ZK_CONFIG_PATH);

  return {
    // Bug 6: walletProvider required for private state sync
    privateStateProvider: levelPrivateStateProvider<typeof PRIVATE_STATE_ID>({
      privateStateStoreName: 'data-subject-rights-private-state',
      walletProvider: bridge,
    }),
    publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),
    zkConfigProvider,
    // Bug 6: zkConfigProvider must be passed as second arg to proof provider
    proofProvider: httpClientProofProvider(config.proofServer, zkConfigProvider),
    walletProvider: bridge,
    midnightProvider: bridge,
  };
}

// ------------------------------------------------------------------
// Deploy
// ------------------------------------------------------------------
async function deploy(providers: Providers) {
  console.log('[5/6] Deploying DataSubjectRights...');
  console.log('  Generating ZK proof + submitting deploy tx...\n');

  const contract = await deployContract(providers, {
    compiledContract,
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState: {} as PrivateState,
  });

  const addr = contract.deployTxData.public.contractAddress;
  console.log(`  Deployed! ✓`);
  console.log(`  Address: ${addr}`);
  console.log(`  Block:   ${contract.deployTxData.public.blockHeight}`);
  console.log(`  Tx ID:   ${contract.deployTxData.public.txId}`);
  return contract;
}

// ------------------------------------------------------------------
// Join existing deployment
// ------------------------------------------------------------------
async function join(providers: Providers, contractAddress: string) {
  console.log(`[5/6] Joining DataSubjectRights at ${contractAddress}...`);
  const contract = await findDeployedContract(providers, {
    contractAddress,
    compiledContract,
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState: {} as PrivateState,
  });
  console.log(`  Joined ✓`);
  return contract;
}

// ------------------------------------------------------------------
// Helper: compute request_id as sha256(subjectId + controllerId + reqType + nonce)
// This mirrors the off-chain convention documented in the contract header.
// The hash ensures no PII on-chain while uniquely identifying each request.
// ------------------------------------------------------------------
function computeRequestId(
  subjectId: Buffer,
  controllerId: Buffer,
  reqType: number,
  nonce: number,
): Buffer {
  return createHash('sha256')
    .update(subjectId)
    .update(controllerId)
    .update(Buffer.from([reqType]))
    .update(Buffer.from([nonce]))
    .digest();
}

// ------------------------------------------------------------------
// Demo: LGPD Art. 18 rights request lifecycle
//
// Scenario: Data subject "Carlos Mendez" exercises rights against controller
// "Acme Fintech LTDA" (identified only by hash — no PII on-chain).
//
// Shows:
//   1. Submit type-1 (confirmation) request → status=open
//   2. Fulfill within 15-day deadline → status=fulfilled
//   3. Submit type-2 (data access) request → status=open
//   4. Reject with justification → status=rejected
//   5. Query counters (total_requests, total_fulfilled, total_rejected, total_overdue)
// ------------------------------------------------------------------
async function runDemo(contract: any, deployBlock: number) {
  console.log('\n--- Demo: LGPD Art. 18 Rights Request Lifecycle ---');

  // Subject and controller identifiers — only their hashes go on-chain
  const subjectEmail = 'carlos.mendez@example.com.br';
  const controllerCNPJ = '00.000.000/0001-00';  // fictional CNPJ

  const subjectId = createHash('sha256').update(subjectEmail).digest();
  const controllerId = createHash('sha256').update(controllerCNPJ).digest();

  // Block at which we "submit" — in demo we use deployBlock + 1 as a proxy
  const submittedBlock = deployBlock + 1;

  // ---------------------------------------------------------------------------
  // 1. Submit Art. 18 I — confirmation request (is my data being processed?)
  // ---------------------------------------------------------------------------
  const reqId1 = computeRequestId(subjectId, controllerId, 1, 0);
  console.log(`\n[1] submitRequest — type 1 (Art. 18 I: confirmation)`);
  console.log(`    request_id: sha256(subjectId || controllerId || type=1 || nonce=0)`);
  console.log(`    submitted_block: ${submittedBlock}`);
  const submitResult1 = await contract.callTx.submitRequest(reqId1, 1, submittedBlock);
  console.log(`    Tx: ${submitResult1.public.txId} (block ${submitResult1.public.blockHeight})`);

  console.log('\n[2] getRequestStatus (request 1)');
  const status1Open = await contract.callTx.getRequestStatus(reqId1);
  console.log(`    Status: ${status1Open.data} (expected 1 = open)`);

  // ---------------------------------------------------------------------------
  // 2. Fulfill within LGPD Art. 19 15-day deadline
  //    21600 blocks = 15 days at 1 block/min; we resolve at block+100 (well within deadline)
  // ---------------------------------------------------------------------------
  const fulfilledBlock = submittedBlock + 100;
  console.log(`\n[3] fulfillRequest — controller responds within deadline`);
  console.log(`    resolved_block: ${fulfilledBlock} (${fulfilledBlock - submittedBlock} blocks after submission)`);
  const fulfillResult = await contract.callTx.fulfillRequest(reqId1, fulfilledBlock);
  console.log(`    Tx: ${fulfillResult.public.txId}`);

  console.log('\n[4] getRequestStatus (request 1 post-fulfill)');
  const status1Fulfilled = await contract.callTx.getRequestStatus(reqId1);
  console.log(`    Status: ${status1Fulfilled.data} (expected 2 = fulfilled)`);

  // ---------------------------------------------------------------------------
  // 3. Submit Art. 18 II — data access request (provide a copy of my data)
  // ---------------------------------------------------------------------------
  const reqId2 = computeRequestId(subjectId, controllerId, 2, 0);
  const submittedBlock2 = fulfilledBlock + 10;
  console.log(`\n[5] submitRequest — type 2 (Art. 18 II: data access)`);
  console.log(`    submitted_block: ${submittedBlock2}`);
  const submitResult2 = await contract.callTx.submitRequest(reqId2, 2, submittedBlock2);
  console.log(`    Tx: ${submitResult2.public.txId}`);

  // ---------------------------------------------------------------------------
  // 4. Reject the access request (LGPD Art. 18 §4 — rejection with justification)
  //    Reason is stored off-chain (e.g., in a case management system)
  // ---------------------------------------------------------------------------
  const rejectedBlock = submittedBlock2 + 50;
  console.log(`\n[6] rejectRequest — Art. 18 §4 rejection (justification stored off-chain)`);
  console.log(`    resolved_block: ${rejectedBlock}`);
  const rejectResult = await contract.callTx.rejectRequest(reqId2, rejectedBlock);
  console.log(`    Tx: ${rejectResult.public.txId}`);

  console.log('\n[7] getRequestStatus (request 2 post-reject)');
  const status2Rejected = await contract.callTx.getRequestStatus(reqId2);
  console.log(`    Status: ${status2Rejected.data} (expected 3 = rejected)`);

  // ---------------------------------------------------------------------------
  // 5. Read aggregate counters (ANPD audit readiness)
  // ---------------------------------------------------------------------------
  console.log('\n[8] Aggregate counters (ANPD audit readiness)');

  const totalRequests = await contract.callTx.getTotalRequests();
  console.log(`    Total requests:  ${totalRequests.data} (expected 2)`);

  const totalFulfilled = await contract.callTx.getTotalFulfilled();
  console.log(`    Total fulfilled: ${totalFulfilled.data} (expected 1)`);

  const totalRejected = await contract.callTx.getTotalRejected();
  console.log(`    Total rejected:  ${totalRejected.data} (expected 1)`);

  const totalOverdue = await contract.callTx.getTotalOverdue();
  console.log(`    Total overdue:   ${totalOverdue.data} (expected 0 — no overdue in this demo)`);

  // ---------------------------------------------------------------------------
  // 6. Show how to query a specific request's type and submission block
  // ---------------------------------------------------------------------------
  console.log('\n[9] getRequestType + getRequestSubmittedBlock (request 1)');
  const type1 = await contract.callTx.getRequestType(reqId1);
  const block1 = await contract.callTx.getRequestSubmittedBlock(reqId1);
  console.log(`    Type: ${type1.data} (expected 1 = confirmation/Art. 18 I)`);
  console.log(`    Submitted block: ${block1.data}`);

  console.log('\n    Demo complete ✓');
  console.log('    Note: markRequestOverdue() requires current_block >= submitted_block + 21600.');
  console.log('          Test it by submitting a request and waiting 15 days (or in standalone');
  console.log('          by setting submitted_block = 1 and current_block >= 21601).');
}

// ------------------------------------------------------------------
// Faucet request
// ------------------------------------------------------------------
async function requestFaucet(url: string, address: string) {
  try {
    console.log(`  Requesting tNIGHT from faucet for ${address}...`);
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ address }),
    });
    console.log(res.ok ? '  Faucet request submitted ✓' : `  Faucet ${res.status}: ${await res.text()}`);
  } catch (e) {
    console.log(`  Faucet error: ${e}`);
  }
}

// ------------------------------------------------------------------
// Main
// ------------------------------------------------------------------
async function main() {
  const { values } = parseArgs({
    options: {
      network: { type: 'string', default: process.env.MIDNIGHT_NETWORK ?? 'preprod' },
      seed:    { type: 'string' },
      join:    { type: 'string' },
      faucet:  { type: 'boolean', default: false },
      demo:    { type: 'boolean', default: false },
    },
  });

  const net = values.network ?? 'preprod';
  const config = NETWORKS[net];
  if (!config) { console.error(`Unknown network: ${net}`); process.exit(1); }

  console.log('='.repeat(60));
  console.log('  DPO2U DataSubjectRights — Midnight Network');
  console.log(`  Network: ${net.toUpperCase()}`);
  console.log('='.repeat(60));
  console.log(`  Indexer:      ${config.indexer}`);
  console.log(`  Proof Server: ${config.proofServer}`);
  console.log(`  ZK Assets:    ${ZK_CONFIG_PATH}`);
  console.log('');

  // CRITICAL: must call setNetworkId() before any contract operation
  setNetworkId(config.networkId);

  const seed = values.seed ?? process.env.MIDNIGHT_SEED ?? toHex(Buffer.from(generateRandomSeed()));
  console.log(`  Seed: ${seed}`);
  console.log('  ⚠️  Save this seed to restore your wallet!\n');

  const ctx = await buildWallet(config, seed);
  const addr = ctx.unshieldedKeystore.getBech32Address();
  console.log(`  Address: ${addr}\n`);

  await waitForSync(ctx.wallet);

  if (values.faucet && config.faucetUrl) {
    await requestFaucet(config.faucetUrl, addr);
  }

  console.log('[4/6] Checking balance...');
  await checkBalance(ctx.wallet);

  const providers = await configureProviders(ctx, config);

  let contract;
  if (values.join) {
    contract = await join(providers, values.join);
  } else {
    contract = await deploy(providers);
  }

  const deployBlock = contract.deployTxData.public.blockHeight as number;

  if (values.demo) {
    await runDemo(contract, deployBlock);
  }

  // Save deployment info
  const deployInfo = {
    contract: 'DataSubjectRights',
    network: net,
    contractAddress: contract.deployTxData.public.contractAddress,
    blockHeight: deployBlock,
    txId: contract.deployTxData.public.txId,
    walletAddress: addr,
    timestamp: new Date().toISOString(),
    lgpdCoverage: ['Art. 18 I-IX (rights requests)', 'Art. 19 (15-day deadline)', 'Art. 18 §4 (rejection)'],
    sdkVersions: {
      'midnight-js': '3.0.0-3.1.0',
      'wallet-sdk-facade': '2.0.0',
      'compact-runtime': '0.14.0',
      'ledger-v7': '7.0.0',
    },
  };

  console.log('\n' + '='.repeat(60));
  console.log('  DEPLOYMENT SUMMARY');
  console.log('='.repeat(60));
  console.log(`  Network:  ${net}`);
  console.log(`  Contract: ${deployInfo.contractAddress}`);
  console.log(`  Block:    ${deployInfo.blockHeight}`);
  console.log(`  Tx:       ${deployInfo.txId}`);
  console.log(`  Seed:     ${seed}`);
  console.log(`  Address:  ${addr}`);
  console.log('='.repeat(60));

  const deployPath = path.resolve(
    new URL(import.meta.url).pathname,
    '..', '..', `deployment-data-subject-rights-${net}.json`,
  );
  fs.writeFileSync(deployPath, JSON.stringify(deployInfo, null, 2));
  console.log(`\n  Saved to: ${deployPath}`);

  await ctx.wallet.stop();
  process.exit(0);
}

main().catch((err) => {
  console.error('\nDeploy failed:', err);
  process.exit(1);
});
