/**
 * deploy-consent-registry.ts — Deploy ConsentRegistry to Midnight Network
 *
 * Implements LGPD/GDPR consent management on-chain.
 * Based on deploy-preprod.ts from dpo2u-midnight-agent-dna.
 *
 * Usage:
 *   npx tsx scripts/deploy-consent-registry.ts [options]
 *
 * Options:
 *   --network   preprod | preview | standalone  (default: preprod)
 *   --seed      <64-char hex>  HD wallet seed
 *   --join      <contract-address>  join existing deployment
 *   --faucet    request tNIGHT from faucet (preprod/preview only)
 *   --demo      run demo: grantConsent, revokeConsent, query status
 *
 * Prerequisites:
 *   1. compactc 0.29.0 installed + Bug 1 fix applied (see scripts/compile-contracts.sh)
 *   2. ./scripts/compile-contracts.sh --contract ConsentRegistry
 *   3. rm -f .npmrc  (Bug 2: npm.midnight.network does not exist)
 *   4. npm install
 *   5. Proof server running on port 6300 (docker-compose up -d)
 *
 * SDK Versions (PREPROD — SDK-VERSION-MATRIX.md):
 *   @midnight-ntwrk/midnight-js-*       3.0.0–3.1.0
 *   @midnight-ntwrk/wallet-sdk-facade   2.0.0  (WalletFacade.init API)
 *   @midnight-ntwrk/ledger-v7           7.0.0
 *   @midnight-ntwrk/compact-runtime     0.14.0
 *   midnight-node Docker                0.21.0
 *   indexer-standalone Docker           3.1.0
 *   proof-server Docker                 7.0.0
 *
 * CRITICAL RULES from WORKAROUND-GUIDE.md:
 *   - NEVER use npm.midnight.network (does not exist — Bug 2)
 *   - NEVER mix preprod/preview SDK versions (silent sync failures — Bug 3)
 *   - NEVER use wallet.signRecipe() — use WalletFacade.init + finalizeRecipe (Bug 5)
 *   - ALWAYS call setNetworkId() before any contract operation
 *   - ALWAYS add smoldot override to package.json (Bug 7)
 */

import 'dotenv/config';
import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import {
  type MidnightProvider,
  type WalletProvider,
  type MidnightProviders,
} from '@midnight-ntwrk/midnight-js-types';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { toHex } from '@midnight-ntwrk/midnight-js-utils';
import { CompiledContract, type ImpureCircuitId } from '@midnight-ntwrk/compact-js';

import { WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { DustWallet } from '@midnight-ntwrk/wallet-sdk-dust-wallet';
import { HDWallet, Roles, generateRandomSeed } from '@midnight-ntwrk/wallet-sdk-hd';
import { ShieldedWallet } from '@midnight-ntwrk/wallet-sdk-shielded';
import {
  createKeystore,
  PublicKey,
  UnshieldedWallet,
} from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import * as ledgerLib from '@midnight-ntwrk/ledger-v7';

// Generated by: ./scripts/compile-contracts.sh --contract ConsentRegistry
import * as ConsentRegistry from '../build/ConsentRegistry/contract/index.js';

import * as Rx from 'rxjs';
import { WebSocket } from 'ws';
import { Buffer } from 'buffer';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { parseArgs } from 'node:util';
import * as fs from 'node:fs';

// WebSocket polyfill required by GraphQL subscriptions in Node.js
// @ts-expect-error: global override for graphql-ws
globalThis.WebSocket = WebSocket;

// ------------------------------------------------------------------
// Types
// ------------------------------------------------------------------
type PrivateState = Record<string, never>;
type ConsentRegistryContract = ConsentRegistry.Contract<PrivateState>;
type CircuitIds = ImpureCircuitId<ConsentRegistryContract>;

const PRIVATE_STATE_ID = 'consentRegistryPrivateState' as const;
type Providers = MidnightProviders<CircuitIds, typeof PRIVATE_STATE_ID, PrivateState>;

// ------------------------------------------------------------------
// Network Configuration
// Matches SDK-VERSION-MATRIX.md verified combinations
// ------------------------------------------------------------------
interface NetworkConfig {
  indexer: string;
  indexerWS: string;
  node: string;
  proofServer: string;
  networkId: string;
  faucetUrl?: string;
}

const NETWORKS: Record<string, NetworkConfig> = {
  preprod: {
    indexer: 'https://indexer.preprod.midnight.network/api/v3/graphql',
    indexerWS: 'wss://indexer.preprod.midnight.network/api/v3/graphql/ws',
    node: 'https://rpc.preprod.midnight.network',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'preprod',
    faucetUrl: 'https://faucet.preprod.midnight.network/api/request-tokens',
  },
  preview: {
    indexer: 'https://indexer.preview.midnight.network/api/v3/graphql',
    indexerWS: 'wss://indexer.preview.midnight.network/api/v3/graphql/ws',
    node: 'https://rpc.preview.midnight.network',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'preview',
    faucetUrl: 'https://faucet.preview.midnight.network/api/request-tokens',
  },
  standalone: {
    indexer: 'http://127.0.0.1:8088/api/v3/graphql',
    indexerWS: 'ws://127.0.0.1:8088/api/v3/graphql/ws',
    node: 'http://127.0.0.1:9944',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'undeployed',
  },
};

// ------------------------------------------------------------------
// ZK Assets path (output of compactc compilation)
// ------------------------------------------------------------------
const ZK_CONFIG_PATH = path.resolve(
  new URL(import.meta.url).pathname,
  '..', '..', 'build', 'ConsentRegistry',
);

// ------------------------------------------------------------------
// Compiled Contract
// ------------------------------------------------------------------
const compiledContract = CompiledContract.make(
  'ConsentRegistry',
  ConsentRegistry.Contract,
).pipe(
  CompiledContract.withVacantWitnesses,
  CompiledContract.withCompiledFileAssets(ZK_CONFIG_PATH),
);

// ------------------------------------------------------------------
// HD Key Derivation (64-char hex seed → shielded + dust + unshielded keys)
// ------------------------------------------------------------------
function deriveKeys(seed: string) {
  const hd = HDWallet.fromSeed(Buffer.from(seed, 'hex'));
  if (hd.type !== 'seedOk') throw new Error('Bad HD seed — must be 64 hex chars');

  const result = hd.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust])
    .deriveKeysAt(0);

  if (result.type !== 'keysDerived') throw new Error('Key derivation failed');
  hd.hdWallet.clear();
  return result.keys;
}

// ------------------------------------------------------------------
// Wallet initialization — WalletFacade.init() API (wallet-sdk-facade 2.0.0)
// See SDK-VERSION-MATRIX.md for API differences between 1.0.0 and 2.0.0
// ------------------------------------------------------------------
async function buildWallet(config: NetworkConfig, seed: string) {
  console.log('[1/6] Deriving HD keys from seed...');
  const keys = deriveKeys(seed);
  const shieldedSecretKeys = ledgerLib.ZswapSecretKeys.fromSeed(keys[Roles.Zswap]);
  const dustSecretKey = ledgerLib.DustSecretKey.fromSeed(keys[Roles.Dust]);
  const unshieldedKeystore = createKeystore(keys[Roles.NightExternal], config.networkId);

  const walletConfig = {
    networkId: config.networkId,
    indexerClientConnection: {
      indexerHttpUrl: config.indexer,
      indexerWsUrl: config.indexerWS,
    },
    provingServerUrl: new URL(config.proofServer),
    relayURL: new URL(config.node.replace(/^http/, 'ws')),
    costParameters: {
      additionalFeeOverhead: 300_000_000_000_000n,
      feeBlocksMargin: 5,
    },
  };

  console.log('[2/6] Initializing WalletFacade...');
  const wallet = await WalletFacade.init({
    configuration: walletConfig,
    shielded: (cfg: any) => ShieldedWallet(cfg).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (cfg: any) => UnshieldedWallet(cfg).startWithPublicKey(
      PublicKey.fromKeyStore(unshieldedKeystore),
    ),
    dust: (cfg: any) => DustWallet(cfg).startWithSecretKey(
      dustSecretKey,
      ledgerLib.LedgerParameters.initialParameters().dust,
    ),
  });

  return { wallet, shieldedSecretKeys, dustSecretKey, unshieldedKeystore, seed };
}

// ------------------------------------------------------------------
// Wait for wallet sync
// ------------------------------------------------------------------
async function waitForSync(wallet: WalletFacade) {
  console.log('[3/6] Syncing wallet (first sync may take 10-30 min)...');

  const sub = wallet.state().pipe(
    Rx.throttleTime(15_000),
  ).subscribe((state) => {
    const synced = state.isSynced ? 'SYNCED' : 'syncing...';
    const nativeToken = ledgerLib.unshieldedToken().raw;
    const unshieldedBal = state.unshielded?.balances?.[nativeToken] ?? 0n;
    const dustCount = state.dust?.availableCoins?.length ?? 0;
    console.log(`  [${new Date().toISOString().slice(11,19)}] ${synced} | unshielded: ${unshieldedBal} | dust coins: ${dustCount}`);
  });

  try {
    await wallet.waitForSyncedState();
  } finally {
    sub.unsubscribe();
  }
  console.log('  Wallet synced ✓');
}

// ------------------------------------------------------------------
// Balance check + faucet wait
// ------------------------------------------------------------------
async function checkBalance(wallet: WalletFacade): Promise<bigint> {
  const state = await wallet.waitForSyncedState();
  const nativeToken = ledgerLib.unshieldedToken().raw;
  const balance = state.unshielded.balances[nativeToken] ?? 0n;

  if (balance > 0n) {
    console.log(`  tNIGHT balance: ${balance.toLocaleString()}`);
    return balance;
  }

  console.log('  No tNIGHT balance. Waiting for incoming tokens...');
  console.log('  Fund at: https://faucet.preprod.midnight.network/');

  return Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(10_000),
      Rx.filter((s) => s.isSynced),
      Rx.map((s) => s.unshielded.balances[nativeToken] ?? 0n),
      Rx.filter((b) => b > 0n),
    ),
  );
}

// ------------------------------------------------------------------
// Provider bridge — WalletProvider + MidnightProvider
// Bug 5 fix: use finalizeRecipe, NOT wallet.signRecipe() which corrupts proof markers
// ------------------------------------------------------------------
async function createProviderBridge(
  ctx: Awaited<ReturnType<typeof buildWallet>>,
): Promise<WalletProvider & MidnightProvider> {
  const state = await ctx.wallet.waitForSyncedState();
  return {
    getCoinPublicKey: () => state.shielded.coinPublicKey.toHexString(),
    getEncryptionPublicKey: () => state.shielded.encryptionPublicKey.toHexString(),
    async balanceTx(tx: any, ttl?: Date) {
      const recipe = await ctx.wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys: ctx.shieldedSecretKeys, dustSecretKey: ctx.dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      // Bug 5: use finalizeRecipe — do NOT call wallet.signRecipe() directly
      return ctx.wallet.finalizeRecipe(recipe);
    },
    submitTx(tx: any) {
      return ctx.wallet.submitTransaction(tx) as any;
    },
  };
}

// ------------------------------------------------------------------
// Configure all midnight-js providers
// Bug 6 fix: pass walletProvider to levelPrivateStateProvider
// ------------------------------------------------------------------
async function configureProviders(
  ctx: Awaited<ReturnType<typeof buildWallet>>,
  config: NetworkConfig,
): Promise<Providers> {
  const bridge = await createProviderBridge(ctx);
  const zkConfigProvider = new NodeZkConfigProvider<CircuitIds>(ZK_CONFIG_PATH);

  return {
    // Bug 6: walletProvider required for private state sync
    privateStateProvider: levelPrivateStateProvider<typeof PRIVATE_STATE_ID>({
      privateStateStoreName: 'consent-registry-private-state',
      walletProvider: bridge,
    }),
    publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),
    zkConfigProvider,
    // Bug 6: zkConfigProvider must be passed as second arg to proof provider
    proofProvider: httpClientProofProvider(config.proofServer, zkConfigProvider),
    walletProvider: bridge,
    midnightProvider: bridge,
  };
}

// ------------------------------------------------------------------
// Deploy
// ------------------------------------------------------------------
async function deploy(providers: Providers) {
  console.log('[5/6] Deploying ConsentRegistry...');
  console.log('  Generating ZK proof + submitting deploy tx...\n');

  const contract = await deployContract(providers, {
    compiledContract,
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState: {} as PrivateState,
  });

  const addr = contract.deployTxData.public.contractAddress;
  console.log(`  Deployed! ✓`);
  console.log(`  Address: ${addr}`);
  console.log(`  Block:   ${contract.deployTxData.public.blockHeight}`);
  console.log(`  Tx ID:   ${contract.deployTxData.public.txId}`);
  return contract;
}

// ------------------------------------------------------------------
// Join existing deployment
// ------------------------------------------------------------------
async function join(providers: Providers, contractAddress: string) {
  console.log(`[5/6] Joining ConsentRegistry at ${contractAddress}...`);
  const contract = await findDeployedContract(providers, {
    contractAddress,
    compiledContract,
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState: {} as PrivateState,
  });
  console.log(`  Joined ✓`);
  return contract;
}

// ------------------------------------------------------------------
// Demo: grant/update/revoke consent, query state
// Demonstrates full LGPD consent lifecycle
// ------------------------------------------------------------------
async function runDemo(contract: any) {
  console.log('\n--- Demo: LGPD Consent Lifecycle ---');

  // Subject ID: sha256 hash of a fictional email (PII never on-chain)
  const subjectEmail = 'ana.silva@example.com.br';
  const subjectId = createHash('sha256').update(subjectEmail).digest();

  // LGPD Art. 8: consent must be for specific purposes
  // purposes bitmask: 0x01 (essential) | 0x02 (analytics) = 3
  const purposes = 3;
  const policyVersion = 1;

  console.log(`\n[1] grantConsent — subject: sha256("${subjectEmail}")`);
  console.log(`    purposes: ${purposes} (essential + analytics), policy v${policyVersion}`);
  const grantResult = await contract.callTx.grantConsent(subjectId, purposes, policyVersion);
  console.log(`    Tx: ${grantResult.public.txId} (block ${grantResult.public.blockHeight})`);

  console.log('\n[2] getConsentStatus');
  const statusResult = await contract.callTx.getConsentStatus(subjectId);
  console.log(`    Status: ${statusResult.data} (expected 1 = active)`);

  console.log('\n[3] getConsentPurposes');
  const purposesResult = await contract.callTx.getConsentPurposes(subjectId);
  console.log(`    Purposes bitmask: ${purposesResult.data} (expected 3)`);

  console.log('\n[4] updateConsentPurposes — remove analytics (keep only essential = 1)');
  const updateResult = await contract.callTx.updateConsentPurposes(subjectId, 1, policyVersion);
  console.log(`    Tx: ${updateResult.public.txId}`);

  console.log('\n[5] revokeConsent — LGPD Art. 8 §5 withdrawal');
  const revokeResult = await contract.callTx.revokeConsent(subjectId);
  console.log(`    Tx: ${revokeResult.public.txId}`);

  console.log('\n[6] getConsentStatus (post-revoke)');
  const finalStatus = await contract.callTx.getConsentStatus(subjectId);
  console.log(`    Status: ${finalStatus.data} (expected 2 = revoked)`);

  console.log('\n[7] getTotalConsentsGranted');
  const totalGranted = await contract.callTx.getTotalConsentsGranted();
  console.log(`    Total consents granted: ${totalGranted.data}`);

  console.log('\n[8] getTotalRevocations');
  const totalRevoked = await contract.callTx.getTotalRevocations();
  console.log(`    Total revocations: ${totalRevoked.data}`);

  console.log('\n    Demo complete ✓');
}

// ------------------------------------------------------------------
// Faucet request
// ------------------------------------------------------------------
async function requestFaucet(url: string, address: string) {
  try {
    console.log(`  Requesting tNIGHT from faucet for ${address}...`);
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ address }),
    });
    console.log(res.ok ? '  Faucet request submitted ✓' : `  Faucet ${res.status}: ${await res.text()}`);
  } catch (e) {
    console.log(`  Faucet error: ${e}`);
  }
}

// ------------------------------------------------------------------
// Main
// ------------------------------------------------------------------
async function main() {
  const { values } = parseArgs({
    options: {
      network: { type: 'string', default: process.env.MIDNIGHT_NETWORK ?? 'preprod' },
      seed:    { type: 'string' },
      join:    { type: 'string' },
      faucet:  { type: 'boolean', default: false },
      demo:    { type: 'boolean', default: false },
    },
  });

  const net = values.network ?? 'preprod';
  const config = NETWORKS[net];
  if (!config) { console.error(`Unknown network: ${net}`); process.exit(1); }

  console.log('='.repeat(60));
  console.log('  DPO2U ConsentRegistry — Midnight Network');
  console.log(`  Network: ${net.toUpperCase()}`);
  console.log('='.repeat(60));
  console.log(`  Indexer:      ${config.indexer}`);
  console.log(`  Proof Server: ${config.proofServer}`);
  console.log(`  ZK Assets:    ${ZK_CONFIG_PATH}`);
  console.log('');

  // CRITICAL: must call setNetworkId() before any contract operation
  setNetworkId(config.networkId);

  const seed = values.seed ?? process.env.MIDNIGHT_SEED ?? toHex(Buffer.from(generateRandomSeed()));
  console.log(`  Seed: ${seed}`);
  console.log('  ⚠️  Save this seed to restore your wallet!\n');

  const ctx = await buildWallet(config, seed);
  const addr = ctx.unshieldedKeystore.getBech32Address();
  console.log(`  Address: ${addr}\n`);

  await waitForSync(ctx.wallet);

  if (values.faucet && config.faucetUrl) {
    await requestFaucet(config.faucetUrl, addr);
  }

  console.log('[4/6] Checking balance...');
  await checkBalance(ctx.wallet);

  const providers = await configureProviders(ctx, config);

  let contract;
  if (values.join) {
    contract = await join(providers, values.join);
  } else {
    contract = await deploy(providers);
  }

  if (values.demo) {
    await runDemo(contract);
  }

  // Save deployment info
  const deployInfo = {
    contract: 'ConsentRegistry',
    network: net,
    contractAddress: contract.deployTxData.public.contractAddress,
    blockHeight: contract.deployTxData.public.blockHeight,
    txId: contract.deployTxData.public.txId,
    walletAddress: addr,
    timestamp: new Date().toISOString(),
    sdkVersions: {
      'midnight-js': '3.0.0-3.1.0',
      'wallet-sdk-facade': '2.0.0',
      'compact-runtime': '0.14.0',
      'ledger-v7': '7.0.0',
    },
  };

  console.log('\n' + '='.repeat(60));
  console.log('  DEPLOYMENT SUMMARY');
  console.log('='.repeat(60));
  console.log(`  Network:  ${net}`);
  console.log(`  Contract: ${deployInfo.contractAddress}`);
  console.log(`  Block:    ${deployInfo.blockHeight}`);
  console.log(`  Tx:       ${deployInfo.txId}`);
  console.log(`  Seed:     ${seed}`);
  console.log(`  Address:  ${addr}`);
  console.log('='.repeat(60));

  const deployPath = path.resolve(
    new URL(import.meta.url).pathname,
    '..', '..', `deployment-consent-registry-${net}.json`,
  );
  fs.writeFileSync(deployPath, JSON.stringify(deployInfo, null, 2));
  console.log(`\n  Saved to: ${deployPath}`);

  await ctx.wallet.stop();
  process.exit(0);
}

main().catch((err) => {
  console.error('\nDeploy failed:', err);
  process.exit(1);
});
