/**
 * deploy-all.ts — Deploy all 3 DPO2U compliance contracts in a single wallet session
 *
 * Syncs the wallet ONCE and deploys ConsentRegistry, DataAuditLog, and DataSubjectRights
 * in sequence. Running the 3 individual deploy scripts separately would sync the wallet
 * 3 times (potentially 20-60 min each on preprod); this script reduces that to one sync.
 *
 * Usage:
 *   npx tsx scripts/deploy-all.ts [options]
 *
 * Options:
 *   --network   preprod | preview | standalone  (default: standalone)
 *   --seed      <64-char hex>  HD wallet seed (saved to deploy output — store securely!)
 *   --faucet    request tNIGHT from faucet after sync (preprod/preview only)
 *   --skip-cr   skip ConsentRegistry deployment (e.g. already deployed)
 *   --skip-dal  skip DataAuditLog deployment
 *   --skip-dsr  skip DataSubjectRights deployment
 *
 * Prerequisites:
 *   ./scripts/compile-contracts.sh        (compiles all 3 contracts)
 *   npm install                           (rm -f .npmrc first — Bug 2)
 *   docker compose up -d                  (midnight-node, indexer, proof-server)
 *
 * Saves deployment info to (consumed by interact-full-suite.ts):
 *   deployment-consent-registry-<network>.json
 *   deployment-data-audit-log-<network>.json
 *   deployment-data-subject-rights-<network>.json
 *
 * SDK Versions (preprod — SDK-VERSION-MATRIX.md):
 *   @midnight-ntwrk/midnight-js-*       3.0.0–3.1.0
 *   @midnight-ntwrk/wallet-sdk-facade   2.0.0  (WalletFacade.init API)
 *   @midnight-ntwrk/ledger-v7           7.0.0
 *   @midnight-ntwrk/compact-runtime     0.14.0
 *   midnight-node Docker                0.21.0
 *   indexer-standalone Docker           3.1.0
 *   proof-server Docker                 7.0.0
 *
 * CRITICAL RULES from WORKAROUND-GUIDE.md:
 *   - NEVER use npm.midnight.network (does not exist — Bug 2)
 *   - NEVER mix preprod/preview SDK versions (silent sync failures — Bug 3)
 *   - NEVER use wallet.signRecipe() — use WalletFacade.init + finalizeRecipe (Bug 5)
 *   - ALWAYS call setNetworkId() before any contract operation (Bug 4)
 *   - ALWAYS add smoldot override to package.json (Bug 7)
 *   - ALWAYS pass walletProvider to levelPrivateStateProvider (Bug 6)
 */

import 'dotenv/config';
import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import {
  type MidnightProvider,
  type WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { toHex } from '@midnight-ntwrk/midnight-js-utils';
import { CompiledContract } from '@midnight-ntwrk/compact-js';

import { WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { DustWallet } from '@midnight-ntwrk/wallet-sdk-dust-wallet';
import { HDWallet, Roles, generateRandomSeed } from '@midnight-ntwrk/wallet-sdk-hd';
import { ShieldedWallet } from '@midnight-ntwrk/wallet-sdk-shielded';
import {
  createKeystore,
  PublicKey,
  UnshieldedWallet,
} from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import * as ledgerLib from '@midnight-ntwrk/ledger-v7';

// Build artifacts — generated by ./scripts/compile-contracts.sh
import * as ConsentRegistry from '../build/ConsentRegistry/contract/index.js';
import * as DataAuditLog from '../build/DataAuditLog/contract/index.js';
import * as DataSubjectRights from '../build/DataSubjectRights/contract/index.js';

import * as Rx from 'rxjs';
import { WebSocket } from 'ws';
import { Buffer } from 'buffer';
import path from 'node:path';
import { parseArgs } from 'node:util';
import * as fs from 'node:fs';
import { fileURLToPath } from 'node:url';

// WebSocket polyfill required by GraphQL subscriptions in Node.js
// @ts-expect-error: global override for graphql-ws
globalThis.WebSocket = WebSocket;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');
const BUILD_DIR = path.resolve(ROOT_DIR, 'build');

// ------------------------------------------------------------------
// Network Configuration — matches SDK-VERSION-MATRIX.md
// ------------------------------------------------------------------
interface NetworkConfig {
  indexer: string;
  indexerWS: string;
  node: string;
  proofServer: string;
  networkId: string;
  faucetUrl?: string;
}

const NETWORKS: Record<string, NetworkConfig> = {
  preprod: {
    indexer: 'https://indexer.preprod.midnight.network/api/v3/graphql',
    indexerWS: 'wss://indexer.preprod.midnight.network/api/v3/graphql/ws',
    node: 'https://rpc.preprod.midnight.network',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'preprod',
    faucetUrl: 'https://faucet.preprod.midnight.network/api/request-tokens',
  },
  preview: {
    indexer: 'https://indexer.preview.midnight.network/api/v3/graphql',
    indexerWS: 'wss://indexer.preview.midnight.network/api/v3/graphql/ws',
    node: 'https://rpc.preview.midnight.network',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'preview',
    faucetUrl: 'https://faucet.preview.midnight.network/api/request-tokens',
  },
  standalone: {
    indexer: 'http://127.0.0.1:8088/api/v3/graphql',
    indexerWS: 'ws://127.0.0.1:8088/api/v3/graphql/ws',
    node: 'http://127.0.0.1:9944',
    proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
    networkId: 'undeployed',
  },
};

// ------------------------------------------------------------------
// Compiled contracts — each needs its own ZK config path
// ------------------------------------------------------------------
type EmptyPrivateState = Record<string, never>;

function makeCompiledContract<C>(name: string, contractModule: { Contract: C }, zkPath: string) {
  return CompiledContract.make(name, contractModule.Contract as any).pipe(
    CompiledContract.withVacantWitnesses,
    CompiledContract.withCompiledFileAssets(zkPath),
  );
}

const CR_ZK_PATH  = path.join(BUILD_DIR, 'ConsentRegistry');
const DAL_ZK_PATH = path.join(BUILD_DIR, 'DataAuditLog');
const DSR_ZK_PATH = path.join(BUILD_DIR, 'DataSubjectRights');

// ------------------------------------------------------------------
// HD Key Derivation — 64-char hex seed → role keys
// ------------------------------------------------------------------
function deriveKeys(seed: string) {
  const hd = HDWallet.fromSeed(Buffer.from(seed, 'hex'));
  if (hd.type !== 'seedOk') throw new Error('Bad HD seed — must be 64 hex chars');
  const result = hd.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust])
    .deriveKeysAt(0);
  if (result.type !== 'keysDerived') throw new Error('Key derivation failed');
  hd.hdWallet.clear();
  return result.keys;
}

// ------------------------------------------------------------------
// Wallet setup — WalletFacade.init() API (wallet-sdk-facade 2.0.0)
// ------------------------------------------------------------------
async function buildWallet(config: NetworkConfig, seed: string) {
  const keys = deriveKeys(seed);
  const shieldedSecretKeys = ledgerLib.ZswapSecretKeys.fromSeed(keys[Roles.Zswap]);
  const dustSecretKey = ledgerLib.DustSecretKey.fromSeed(keys[Roles.Dust]);
  const unshieldedKeystore = createKeystore(keys[Roles.NightExternal], config.networkId);

  const walletConfig = {
    networkId: config.networkId,
    indexerClientConnection: {
      indexerHttpUrl: config.indexer,
      indexerWsUrl: config.indexerWS,
    },
    provingServerUrl: new URL(config.proofServer),
    relayURL: new URL(config.node.replace(/^http/, 'ws')),
    costParameters: {
      additionalFeeOverhead: 300_000_000_000_000n,
      feeBlocksMargin: 5,
    },
  };

  const wallet = await WalletFacade.init({
    configuration: walletConfig,
    shielded: (cfg: any) => ShieldedWallet(cfg).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (cfg: any) => UnshieldedWallet(cfg).startWithPublicKey(
      PublicKey.fromKeyStore(unshieldedKeystore),
    ),
    dust: (cfg: any) => DustWallet(cfg).startWithSecretKey(
      dustSecretKey,
      ledgerLib.LedgerParameters.initialParameters().dust,
    ),
  });

  return { wallet, shieldedSecretKeys, dustSecretKey, unshieldedKeystore };
}

// ------------------------------------------------------------------
// Wallet sync
// ------------------------------------------------------------------
async function waitForSync(wallet: WalletFacade) {
  console.log('[2/5] Syncing wallet (first sync may take 10-30 min on preprod)...');

  const sub = wallet.state().pipe(
    Rx.throttleTime(15_000),
  ).subscribe((state) => {
    const synced = state.isSynced ? 'SYNCED' : 'syncing...';
    const nativeToken = ledgerLib.unshieldedToken().raw;
    const bal = state.unshielded?.balances?.[nativeToken] ?? 0n;
    const dust = state.dust?.availableCoins?.length ?? 0;
    console.log(`  [${new Date().toISOString().slice(11, 19)}] ${synced} | unshielded: ${bal} | dust coins: ${dust}`);
  });

  try {
    await wallet.waitForSyncedState();
  } finally {
    sub.unsubscribe();
  }
  console.log('  Wallet synced ✓');
}

// ------------------------------------------------------------------
// Balance check
// ------------------------------------------------------------------
async function checkBalance(wallet: WalletFacade): Promise<bigint> {
  const state = await wallet.waitForSyncedState();
  const nativeToken = ledgerLib.unshieldedToken().raw;
  const balance = state.unshielded.balances[nativeToken] ?? 0n;

  if (balance > 0n) {
    console.log(`  tNIGHT balance: ${balance.toLocaleString()}`);
    return balance;
  }

  console.log('  No tNIGHT balance — waiting for incoming tokens...');
  console.log('  Fund at: https://faucet.preprod.midnight.network/');

  return Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(10_000),
      Rx.filter((s) => s.isSynced),
      Rx.map((s) => s.unshielded.balances[nativeToken] ?? 0n),
      Rx.filter((b) => b > 0n),
    ),
  );
}

// ------------------------------------------------------------------
// Provider bridge (shared across all 3 deploys)
// Bug 5: use finalizeRecipe — NOT wallet.signRecipe()
// ------------------------------------------------------------------
async function createProviderBridge(ctx: Awaited<ReturnType<typeof buildWallet>>) {
  const state = await ctx.wallet.waitForSyncedState();
  return {
    getCoinPublicKey: () => state.shielded.coinPublicKey.toHexString(),
    getEncryptionPublicKey: () => state.shielded.encryptionPublicKey.toHexString(),
    async balanceTx(tx: any, ttl?: Date) {
      const recipe = await ctx.wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys: ctx.shieldedSecretKeys, dustSecretKey: ctx.dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      return ctx.wallet.finalizeRecipe(recipe);
    },
    submitTx(tx: any) {
      return ctx.wallet.submitTransaction(tx) as any;
    },
  };
}

// ------------------------------------------------------------------
// Build providers for one contract (each needs its own ZK config + private state store)
// Bug 6: walletProvider required by levelPrivateStateProvider
// ------------------------------------------------------------------
function buildProviders(
  bridge: WalletProvider & MidnightProvider,
  config: NetworkConfig,
  zkPath: string,
  privateStateName: string,
) {
  const zkConfigProvider = new NodeZkConfigProvider(zkPath);
  return {
    privateStateProvider: levelPrivateStateProvider({
      privateStateStoreName: privateStateName,
      walletProvider: bridge,
    }),
    publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),
    zkConfigProvider,
    proofProvider: httpClientProofProvider(config.proofServer, zkConfigProvider),
    walletProvider: bridge,
    midnightProvider: bridge,
  };
}

// ------------------------------------------------------------------
// Deploy one contract and save its deployment file
// ------------------------------------------------------------------
async function deployOne(
  label: string,
  compiledContract: any,
  providers: ReturnType<typeof buildProviders>,
  privateStateId: string,
  outputFile: string,
  network: string,
  walletAddress: string,
): Promise<string> {
  console.log(`\n  Generating ZK proof + submitting deploy tx for ${label}...`);

  const contract = await deployContract(providers, {
    compiledContract,
    privateStateId,
    initialPrivateState: {} as EmptyPrivateState,
  });

  const { contractAddress, blockHeight, txId } = contract.deployTxData.public;
  console.log(`  Deployed! ✓`);
  console.log(`  Address: ${contractAddress}`);
  console.log(`  Block:   ${blockHeight}  |  Tx: ${txId}`);

  const deployInfo = {
    contract: label,
    network,
    contractAddress,
    blockHeight,
    txId,
    walletAddress,
    timestamp: new Date().toISOString(),
    sdkVersions: {
      'midnight-js': '3.0.0-3.1.0',
      'wallet-sdk-facade': '2.0.0',
      'compact-runtime': '0.14.0',
      'ledger-v7': '7.0.0',
    },
  };

  fs.writeFileSync(outputFile, JSON.stringify(deployInfo, null, 2));
  console.log(`  Saved: ${path.relative(ROOT_DIR, outputFile)}`);

  return contractAddress;
}

// ------------------------------------------------------------------
// Faucet request
// ------------------------------------------------------------------
async function requestFaucet(url: string, address: string) {
  console.log(`  Requesting tNIGHT from faucet for ${address}...`);
  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ address }),
    });
    console.log(res.ok ? '  Faucet request submitted ✓' : `  Faucet ${res.status}: ${await res.text()}`);
  } catch (e) {
    console.log(`  Faucet error: ${e}`);
  }
}

// ------------------------------------------------------------------
// Main
// ------------------------------------------------------------------
async function main() {
  const { values } = parseArgs({
    options: {
      network:   { type: 'string',  default: process.env.MIDNIGHT_NETWORK ?? 'standalone' },
      seed:      { type: 'string' },
      faucet:    { type: 'boolean', default: false },
      'skip-cr': { type: 'boolean', default: false },
      'skip-dal':{ type: 'boolean', default: false },
      'skip-dsr':{ type: 'boolean', default: false },
    },
  });

  const net = values.network ?? 'standalone';
  const config = NETWORKS[net];
  if (!config) { console.error(`Unknown network: ${net}`); process.exit(1); }

  const skipCR  = values['skip-cr']  ?? false;
  const skipDAL = values['skip-dal'] ?? false;
  const skipDSR = values['skip-dsr'] ?? false;

  console.log('='.repeat(60));
  console.log('  DPO2U Lab — Deploy All Contracts (single wallet sync)');
  console.log(`  Network: ${net.toUpperCase()}`);
  console.log('='.repeat(60));
  console.log(`  Indexer:      ${config.indexer}`);
  console.log(`  Proof Server: ${config.proofServer}`);
  console.log(`  Build Dir:    ${BUILD_DIR}`);
  if (skipCR)  console.log('  Skipping: ConsentRegistry');
  if (skipDAL) console.log('  Skipping: DataAuditLog');
  if (skipDSR) console.log('  Skipping: DataSubjectRights');
  console.log('');

  // CRITICAL: setNetworkId before any contract operation (Bug 4)
  setNetworkId(config.networkId);

  const seed = values.seed ?? process.env.MIDNIGHT_SEED ?? toHex(Buffer.from(generateRandomSeed()));
  console.log(`  Seed: ${seed}`);
  console.log('  Save this seed — it recovers your wallet!\n');

  // [1/5] Build wallet
  console.log('[1/5] Deriving HD keys and initializing WalletFacade...');
  const ctx = await buildWallet(config, seed);
  const walletAddress = ctx.unshieldedKeystore.getBech32Address();
  console.log(`  Address: ${walletAddress}`);

  // [2/5] Sync
  await waitForSync(ctx.wallet);

  // [3/5] Faucet (optional) + balance
  if (values.faucet && config.faucetUrl) {
    await requestFaucet(config.faucetUrl, walletAddress);
  }
  console.log('[3/5] Checking balance...');
  await checkBalance(ctx.wallet);

  // [4/5] Provider bridge (shared by all 3 deploys)
  console.log('[4/5] Building provider bridge...');
  const bridge = await createProviderBridge(ctx);

  // [5/5] Deploy
  console.log('[5/5] Deploying contracts...\n');

  const results: Record<string, string> = {};

  if (!skipCR) {
    console.log('--- [1/3] ConsentRegistry ---');
    const compiledCR = makeCompiledContract('ConsentRegistry', ConsentRegistry, CR_ZK_PATH);
    const providersCR = buildProviders(bridge, config, CR_ZK_PATH, 'cr-private-state');
    results['ConsentRegistry'] = await deployOne(
      'ConsentRegistry',
      compiledCR,
      providersCR,
      'crPrivateState',
      path.join(ROOT_DIR, `deployment-consent-registry-${net}.json`),
      net,
      walletAddress,
    );
  }

  if (!skipDAL) {
    console.log('\n--- [2/3] DataAuditLog ---');
    const compiledDAL = makeCompiledContract('DataAuditLog', DataAuditLog, DAL_ZK_PATH);
    const providersDAL = buildProviders(bridge, config, DAL_ZK_PATH, 'dal-private-state');
    results['DataAuditLog'] = await deployOne(
      'DataAuditLog',
      compiledDAL,
      providersDAL,
      'dalPrivateState',
      path.join(ROOT_DIR, `deployment-data-audit-log-${net}.json`),
      net,
      walletAddress,
    );
  }

  if (!skipDSR) {
    console.log('\n--- [3/3] DataSubjectRights ---');
    const compiledDSR = makeCompiledContract('DataSubjectRights', DataSubjectRights, DSR_ZK_PATH);
    const providersDSR = buildProviders(bridge, config, DSR_ZK_PATH, 'dsr-private-state');
    results['DataSubjectRights'] = await deployOne(
      'DataSubjectRights',
      compiledDSR,
      providersDSR,
      'dsrPrivateState',
      path.join(ROOT_DIR, `deployment-data-subject-rights-${net}.json`),
      net,
      walletAddress,
    );
  }

  // Summary
  console.log('\n' + '='.repeat(60));
  console.log('  DEPLOYMENT SUMMARY');
  console.log('='.repeat(60));
  console.log(`  Network:  ${net}`);
  console.log(`  Wallet:   ${walletAddress}`);
  console.log(`  Seed:     ${seed}`);
  console.log('');
  for (const [name, addr] of Object.entries(results)) {
    console.log(`  ${name}`);
    console.log(`    ${addr}`);
  }
  console.log('');
  console.log('  Next: run the full LGPD lifecycle:');
  console.log(`    npx tsx scripts/interact-full-suite.ts --network ${net} --seed ${seed}`);
  console.log('='.repeat(60));

  await ctx.wallet.stop();
  process.exit(0);
}

main().catch((err) => {
  console.error('\nDeploy-all failed:', err);
  process.exit(1);
});
